### ISSUE TITLE
Invalid characters show up as spaces

### ISSUE THREAD

**Issue by alanmutsch** [kieldm/kieldm.github.io#4]
Until 0-9 and A-Z are allowed, the keyTyped function should filter numbers and use toLowerCase.

**Comment by alanmutsch** [comment]
`
function keyPressed() {
  if (keyCode == DELETE || keyCode == BACKSPACE) {
    myText.pop();
  }
}

function keyTyped() {
  if (isNaN(key)) {
    myText.push(key.toLowerCase());
  }
}`

**Comment by kieldm** [comment]
So .pop() deletes one letter from the array? How can I see all the dot syntax options?
